services:
  - type: web
    name: rag-app
    env: node
    buildCommand: apt-get install -y poppler-utils && npm install && npx tsc && cd client && npm install && npm run build && cd ..
    startCommand: npm start
    